export interface FaraGridRow {
    id: number;
    radif: number;
    kodKala: string;
    shomareFanni: string;
    vizhegi1: string;
    vizhegi2: string;
    vizhegi3: string;
    vizhegi4: string;
    namKala: string;
    namEnglisi: string;
    tahvilDahande: string;
    namTahvilDahande: string;
    meqdar: number | string;
    bahayVahed: string;
    mablaghKol: number | string;
}

export const initialRows: FaraGridRow[] = [
    {
        id: 1,
        radif: 1,
        kodKala: "۲۰۰۱۰۰۱۱",
        shomareFanni: "۶۲۶۰۱۳۸۴۲۲۲۳۳",
        vizhegi1: "۱۰۲",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه آناناس ۲۴۰cc",
        namEnglisi: "pineapple 240 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳٬۶۰۰",
        bahayVahed: "",
        mablaghKol: "۳٬۶۰۰",
    },
    {
        id: 2,
        radif: 2,
        kodKala: "۲۰۰۱۰۰۱۱",
        shomareFanni: "۶۲۶۰۱۳۸۴۲۲۲۳۳",
        vizhegi1: "۱۰۳",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه آناناس ۲۴۰cc",
        namEnglisi: "pineapple 240 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳٬۶۰۰",
        bahayVahed: "",
        mablaghKol: "۳٬۶۰۰",
    },
    {
        id: 3,
        radif: 3,
        kodKala: "۲۰۰۱۰۰۱۴",
        shomareFanni: "۶۲۶۰۱۳۸۴۱۰۴۹",
        vizhegi1: "۱۰۳",
        vizhegi2: "۱۰۲",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه انبه ۲۰۰cc",
        namEnglisi: "Mango 200 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳٬۹۶۰",
        bahayVahed: "",
        mablaghKol: "۱٬۸۰۰",
    },
    {
        id: 4,
        radif: 4,
        kodKala: "۲۰۰۱۰۰۹۸",
        shomareFanni: "۶۲۶۰۱۳۸۴۲۰۱۶۱",
        vizhegi1: "۱۰۳",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه سیب ۲۰۰cc",
        namEnglisi: "apple 100 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳۴۰",
        bahayVahed: "",
        mablaghKol: "۳۴۰",
    },
    {
        id: 5,
        radif: 5,
        kodKala: "۲۰۰۱۰۰۴۴",
        shomareFanni: "۶۲۶۰۱۳۸۴۷۰۳۱۹",
        vizhegi1: "۱۰۳",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه انگور ۱lit",
        namEnglisi: "grape 1000 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳۶۰",
        bahayVahed: "",
        mablaghKol: "۳۶۰",
    },
    {
        id: 6,
        radif: 6,
        kodKala: "۲۰۰۱۰۰۸۴",
        shomareFanni: "۶۲۶۰۱۳۸۴۹۹۴۵۷",
        vizhegi1: "۱۰۴",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه پرتقال توسرخ ۱lit",
        namEnglisi: "Red orange 1000 cc t",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۶۰۰",
        bahayVahed: "",
        mablaghKol: "۶۰۰",
    },
    {
        id: 7,
        radif: 7,
        kodKala: "۲۰۰۱۰۰۰",
        shomareFanni: "۶۲۶۰۱۳۸۴۷۰۳۸۹",
        vizhegi1: "۱۰۴",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه سیب ۱lit",
        namEnglisi: "apple 1000 cc",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳۴۰",
        bahayVahed: "",
        mablaghKol: "۳۴۰",
    },
    {
        id: 8,
        radif: 8,
        kodKala: "۲۰۰۱۰۰۴۱",
        shomareFanni: "۶۲۶۰۱۳۸۴۷۰۳۴۱",
        vizhegi1: "۱۰۴",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه سیب کیوی ۱lit",
        namEnglisi: "Mixed apple & kiwi 1 lit",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳۴۰",
        bahayVahed: "",
        mablaghKol: "۳۴۰",
    },
    {
        id: 9,
        radif: 9,
        kodKala: "۲۰۰۱۰۱۱۶",
        shomareFanni: "۶۲۶۰۱۳۸۴۱۰۹۲",
        vizhegi1: "۱۰۴",
        vizhegi2: "۱۰۱",
        vizhegi3: "",
        vizhegi4: "",
        namKala: "آبمیوه لیموناد نعناع ۱lit",
        namEnglisi: "lemonade 1000 cc lit",
        tahvilDahande: "محصول - کارخانه",
        namTahvilDahande: "۳۰۰ل",
        meqdar: "۳۴۰",
        bahayVahed: "",
        mablaghKol: "۳۴۰",
    },
];

export default initialRows;
